//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch SwitcherPanel.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SWITCHERPANEL_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDC_EDIT_ADDRESS                1000
#define IDC_BUTTON_CONNECT              1001
#define IDC_EDIT_NAME                   1002
#define IDC_SLIDER                      1003
#define IDC_COMBO_PROGRAM               1004
#define IDC_EDIT_GUI_CLIENT_IP          1004
#define IDC_COMBO_PREVIEW               1005
#define IDC_EDIT_GUI_SERVER             1005
#define IDC_EDIT_TRANSITION_FRAMES      1006
#define IDC_BUTTON_GUI_CLIENT_CONNECT   1006
#define IDC_EDIT_FTB_FRAMES             1007
#define IDC_EDIT_GUI_CLIENT_PORT        1007
#define IDC_BUTTON_AUTO                 1008
#define IDC_BUTTON_CUT                  1009
#define IDC_BUTTON_FTB                  1010
#define IDC_BUTTON_PROG_BARS            1011
#define IDC_BUTTON_PROG_INPUT_1         1012
#define IDC_BUTTON_AUDIO_MUTE           1013
#define IDC_BUTTON_PROG_INPUT_2         1014
#define IDC_BUTTON_PROG_INPUT_3         1015
#define IDC_BUTTON_PROG_INPUT_4         1016
#define IDC_BUTTON_PROG_INPUT_5         1017
#define IDC_BUTTON_PROG_INPUT_6         1018
#define IDC_SLIDER_MASTER_VOLUME        1019
#define IDC_EDIT_MASTER_BALANCE         1020
#define IDC_BUTTON_PROG_BLACK           1021
#define IDC_BUTTON_PROG_COLOR_1         1022
#define IDC_BUTTON_PROG_COLOR_2         1023
#define IDC_BUTTON_PROG_MEDIA_1         1024
#define IDC_BUTTON_PROG_MEDIA_2         1025
#define IDC_BUTTON_PREV_BARS            1026
#define IDC_BUTTON_PREV_INPUT_1         1027
#define IDC_BUTTON_PREV_INPUT_2         1028
#define IDC_BUTTON_PREV_INPUT_3         1029
#define IDC_BUTTON_PREV_INPUT_4         1030
#define IDC_BUTTON_PREV_INPUT_5         1031
#define IDC_BUTTON_PREV_INPUT_6         1032
#define IDC_EDIT_MASTER_VOLUME          1033
#define IDC_EDIT_OUTPUT                 1034
#define IDC_BUTTON_PREV_BLACK           1035
#define IDC_BUTTON_PREV_COLOR_1         1036
#define IDC_BUTTON_PREV_COLOR_2         1037
#define IDC_BUTTON_PREV_MEDIA_1         1038
#define IDC_BUTTON_PREV_MEDIA_2         1039
#define IDC_SLIDER_GAIN_INPUT1          1040
#define IDC_SLIDER_MASTER_BALANCE       1041
#define IDC_SLIDER_BALANCE_INPUT1       1042
#define IDC_EDIT_BALANCE_INPUT1         1043
#define IDC_EDIT_GAIN_INPUT1            1044
#define IDC_BUTTON_MUTE_INPUT1          1045
#define IDC_EDIT_NAME2                  1046
#define IDC_EDIT_GUI_SERVER_IP          1047
#define IDC_BUTTON_CONNECT_VLC1         1048
#define IDC_BUTTON_GUI_SERVER_CONNECT   1049
#define IDC_LIST_VLC_PLAYLIST1          1050
#define IDC_VLC_PLAY_SELECTED1          1051
#define IDC_EDIT_GUI_SERVER_PORT        1052
#define IDC_CHECK_VLC_START_WITH_TRANSITION1 1056
#define IDC_SPIN_VLC_INPUT1             1058
#define IDC_EDIT_STATUSBAR              1059
#define IDC_SLIDER_GAIN_INPUT2          1076
#define IDC_SLIDER_BALANCE_INPUT2       1077
#define IDC_EDIT_BALANCE_INPUT2         1078
#define IDC_EDIT_GAIN_INPUT2            1079
#define IDC_BUTTON_MUTE_INPUT2          1080
#define IDC_SLIDER_GAIN_INPUT3          1081
#define IDC_SLIDER_BALANCE_INPUT3       1082
#define IDC_EDIT_BALANCE_INPUT3         1083
#define IDC_EDIT_GAIN_INPUT3            1084
#define IDC_BUTTON_MUTE_INPUT3          1085
#define IDC_SLIDER_GAIN_INPUT4          1086
#define IDC_SLIDER_BALANCE_INPUT4       1087
#define IDC_EDIT_BALANCE_INPUT4         1088
#define IDC_EDIT_GAIN_INPUT4            1089
#define IDC_BUTTON_MUTE_INPUT4          1090
#define IDC_SLIDER_GAIN_INPUT5          1091
#define IDC_SLIDER_BALANCE_INPUT5       1092
#define IDC_EDIT_BALANCE_INPUT5         1093
#define IDC_EDIT_GAIN_INPUT5            1094
#define IDC_BUTTON_MUTE_INPUT5          1095
#define IDC_SLIDER_GAIN_INPUT6          1096
#define IDC_SLIDER_BALANCE_INPUT6       1097
#define IDC_EDIT_BALANCE_INPUT6         1098
#define IDC_EDIT_GAIN_INPUT6            1099
#define IDC_BUTTON_MUTE_INPUT6          1100
#define IDC_EDIT_VLC_PORT1              1101
#define IDC_VLC_PAUSE1                  1104
#define IDC_VLC_PLAY1                   1106
#define IDC_CHECK_VLC_STOP_WITH_TRANSITION1 1108
#define IDC_EDIT_VLC_INPUT1             1109
#define IDC_EDIT_VLC_PORT2              1110
#define IDC_BUTTON_CONNECT_VLC2         1111
#define IDC_LIST_VLC_PLAYLIST2          1112
#define IDC_VLC_PLAY_SELECTED2          1113
#define IDC_VLC_PAUSE2                  1114
#define IDC_VLC_PLAY2                   1115
#define IDC_CHECK_VLC_START_WITH_TRANSITION2 1116
#define IDC_CHECK_VLC_STOP_WITH_TRANSITION2 1117
#define IDC_SPIN_VLC_INPUT2             1118
#define IDC_EDIT_VLC_INPUT2             1119
#define IDC_EDIT_VLC_PORT3              1123
#define IDC_BUTTON_CONNECT_VLC3         1124
#define IDC_LIST_VLC_PLAYLIST3          1125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
